/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DongHocPhi;
import model.HocKy;
import model.HocVien;
import model.MonHoc;
import service.impl.adminServiceImpl;

/**
 *
 * @author acer
 */
public class FormDHPAdmin extends javax.swing.JDialog {

    private adminServiceImpl admsv = new adminServiceImpl();
    private DefaultTableModel tbmodel = new DefaultTableModel();
    private DefaultTableModel tbmodel2 = new DefaultTableModel();
    private List<MonHoc> listMH = new ArrayList<>();
    private List<MonHoc> listAllMH = new ArrayList<>();
    private List<HocVien> listHV = new ArrayList<>();
    private List<HocVien> listAllHV = new ArrayList<>();
    private List<DongHocPhi> listDHP = new ArrayList<>();
    private int pageIndex = 1;
    private int pageNumber = 5;

    /**
     * Creates new form FormDHPAdmin
     */
    public FormDHPAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        listDHP = admsv.getListDHP();
        listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
        listAllMH = admsv.getListMonHoc();
        listHV = admsv.listPTHocVien(pageIndex, pageNumber);
        listAllHV = admsv.getAllHocVien();
        loadMonHoc(listMH);
        loadData(listHV);
    }

    public void loadMonHoc(List<MonHoc> list) {
        jTable2.setModel(tbmodel2);
        tbmodel2.setRowCount(0);
        String title[] = {"Tên Môn", "Học Phí", "Thời Lượng"};
        tbmodel2.setColumnIdentifiers(title);
        for (MonHoc mh : list) {
            DecimalFormat formatter = new DecimalFormat("###,###,###");
            String tl = String.valueOf(mh.getThoiLuong()) + " Tháng";
            tbmodel2.addRow(new Object[]{mh.getTenMon(), //hk,
                formatter.format(mh.getHocPhi()) + " VNĐ", tl

            });
        }
    }

    public void fillData(int index) {
        HocVien hv = listHV.get(index);
        jLabel6.setText(hv.getHo() + " " + hv.getTenDem() + " " + hv.getTen());
    }

    public void fillData2(int index2) {
        MonHoc mh = listMH.get(index2);
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        jLabel9.setText(mh.getTenMon());
        String hocPhi = formatter.format(mh.getHocPhi())+" VNĐ";
        jLabel10.setText(hocPhi);
    }

    public void loadData(List<HocVien> list) {
        jTable1.setModel(tbmodel);
        tbmodel.setRowCount(0);
        String title[] = {"Mã HV", "Họ và Tên", "Ngày Sinh", "Giới Tính"};
        tbmodel.setColumnIdentifiers(title);
        for (HocVien hv : list) {
            tbmodel.addRow(new Object[]{hv.getMaHV(),
                hv.getHo() + " " + hv.getTenDem() + " " + hv.getTen(),
                hv.getNgaySinh(),
                hv.isGioiTinh() == true ? "Nam" : "Nữ"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh Sách Học Viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Danh Sách Môn");

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("?/?");

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("?/?");

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Học Viên");

        jLabel6.setText("jLabel6");

        jLabel7.setText("Tên Môn");

        jLabel8.setText("Học Phí");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        jButton1.setText("Tạo Hoá Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tạo Hoá Đơn Đóng Học Phí");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        jButton6.setText("Quay Lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Documents.png"))); // NOI18N
        jButton7.setText("Danh Sách Hoá Đơn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)
                        .addGap(132, 132, 132)
                        .addComponent(jButton7)
                        .addGap(307, 307, 307))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel5)
                .addGap(126, 126, 126)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel5)
                    .addComponent(jButton5))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton7))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (listAllMH.size() % 5 != 0) {
            if (pageIndex <= 1) {
                pageIndex = listAllMH.size() / 5 + 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5 + 1;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            } else {
                pageIndex -= 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5 + 1;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            }
        } else {
            if (pageIndex <= 1) {
                pageIndex = listAllMH.size() / 5;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            } else {
                pageIndex -= 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (listAllMH.size() % 5 != 0) {
            if (pageIndex >= listAllMH.size() / 5 + 1) {
                pageIndex = 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5 + 1;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            } else {
                pageIndex += 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5 + 1;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            }
        } else {
            if (pageIndex >= listAllMH.size() / 5) {
                pageIndex = 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            } else {
                pageIndex += 1;
                listMH = admsv.listPTMonHoc(pageIndex, pageNumber);
                int maxPage = listAllMH.size() / 5;
                jLabel4.setText(pageIndex + "/" + maxPage);
                loadMonHoc(listMH);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (listAllHV.size() % 5 != 0) {
            if (pageIndex <= 1) {
                pageIndex = listAllHV.size() / 5 + 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5 + 1;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            } else {
                pageIndex -= 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5 + 1;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            }
        } else {
            if (pageIndex <= 1) {
                pageIndex = listAllHV.size() / 5;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            } else {
                pageIndex -= 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (listAllHV.size() % 5 != 0) {
            if (pageIndex >= listAllHV.size() / 5 + 1) {
                pageIndex = 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5 + 1;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            } else {
                pageIndex += 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5 + 1;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            }
        } else {
            if (pageIndex >= listAllHV.size() / 5) {
                pageIndex = 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            } else {
                pageIndex += 1;
                listHV = admsv.listPTHocVien(pageIndex, pageNumber);
                int maxPage = listAllHV.size() / 5;
                jLabel5.setText(pageIndex + "/" + maxPage);
                loadData(listHV);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        fillData2(row);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row1 = jTable1.getSelectedRow();
        int row2 = jTable2.getSelectedRow();
        if (row1 >= 0 || row2 >= 0) {
            MonHoc mh = listMH.get(row2);
            HocVien hv = listHV.get(row1);
            DongHocPhi dhp = new DongHocPhi();
            dhp.setIdHocVien(hv.getIdHocVien());
            dhp.setIdMonHoc(mh.getId());
            dhp.setTienDong(mh.getHocPhi());
            for (DongHocPhi donghp : listDHP) {
                if (dhp.getIdHocVien().equalsIgnoreCase(donghp.getIdHocVien())
                        && dhp.getIdMonHoc().equalsIgnoreCase(donghp.getIdMonHoc())) {
                    JOptionPane.showMessageDialog(this, "Học Viên " + hv.getMaHV()
                            + " Đã Đóng Học Phí Môn " + mh.getTenMon());
                    return;
                }
            }
            if (admsv.addDHP(dhp)) {
                admsv.updateTTHV(hv.getIdHocVien());
                JOptionPane.showMessageDialog(this, "Tạo thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Tạo thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Học Viên Và Môn Học!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        menuAdmin mad = new menuAdmin();
        mad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        FormQLDHP f = new FormQLDHP();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDHPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDHPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDHPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDHPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDHPAdmin dialog = new FormDHPAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
