/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.HocVien;
import service.impl.loginImpl;
import service.loginService;

/**
 *
 * @author Dell
 */
public class formDoiMKHV extends javax.swing.JFrame {

    private String maHV;
    private loginService login = new loginImpl();

    /**
     * Creates new form HVdoiMK
     */
    public formDoiMKHV() {
        initComponents();
    }

    public formDoiMKHV(String user) {
        initComponents();
        maHV = user;
    }

    public boolean validatePass(String oldPass, String newPass, String newPassAgain) {
        HocVien nv = login.getoneHV(maHV);
        String check1 = "^[a-zA-Z0-9]{8,49}$";
        String check2 = "^[a-zA-Z0-9]*[0-9]+[a-zA-Z0-9]*";
        String check3 = "^[a-zA-Z0-9]*[a-zA-Z]+[a-zA-Z0-9]*";
        if (oldPass.isEmpty()) {
            lbCheckMK.setText("Mật Khẩu Hiện Tại Chưa Được Nhâp!");
            return false;
        }
        if (!oldPass.equalsIgnoreCase(nv.getMatKhau())) {
            lbCheckMK.setText("Mật Khẩu Sai!");
            return false;
        }
        if (newPass.isEmpty()) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Chưa Được Nhập!");
            return false;
        }
        if (newPass.length() < 8 || newPass.length() > 49) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Tối Thiểu Từ 8 Kí Tự Và Tối Đa 49 Kí Tự!");
            return false;
        }
        if (newPass.equals(oldPass)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Không Được Trùng Với Mật Khẩu Hiện Tại!");
            return false;
        }
        if (!newPass.matches(check3) || !newPass.matches(check2)
                || !newPass.matches(check1)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Phải Đúng Định Dạng!");
            return false;
        }
        if (newPassAgain.isEmpty()) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("");
            lbCheckXNMK.setText("Mật Khẩu Xác Nhận Chưa Được Nhập!");
            return false;
        }
        if (!newPass.equals(newPassAgain)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("");
            lbCheckXNMK.setText("Mật Khẩu Xác Nhận Phải Trùng Với Mật Khẩu Mới!");
            return false;
        }
        lbCheckMK.setText("");
        lbCheckMKMoi.setText("");
        lbCheckXNMK.setText("");
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        changePassStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMKCu = new javax.swing.JTextField();
        hintLabel = new javax.swing.JLabel();
        lbCheckMK = new javax.swing.JLabel();
        btnDoiMK = new javax.swing.JButton();
        lbCheckMKMoi = new javax.swing.JLabel();
        lbCheckXNMK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMKNew = new javax.swing.JPasswordField();
        txtXacNhan = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        hintLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu Mới");

        changePassStatus.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        changePassStatus.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Xác Nhận Mật Khẩu");

        hintLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        hintLabel.setForeground(new java.awt.Color(54, 33, 89));
        hintLabel.setText("Thay đổi mật khẩu. Mật khẩu mới phải đạt tối thiểu 8 ký tự.");

        btnDoiMK.setBackground(new java.awt.Color(204, 255, 153));
        btnDoiMK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(51, 153, 255));
        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnDoiMK.setText("Thay Đổi");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mật Khẩu Cũ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("THAY ĐỔI MẬT KHẨU");

        txtXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXacNhanActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        jButton1.setText("Thoát");

        hintLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        hintLabel1.setForeground(new java.awt.Color(54, 33, 89));
        hintLabel1.setText("Mật Khẩu Có Thể Là Số , Chữ Thường Hoặc In Hoa , Không Được Phép Có Kí Tự Đặc Biệt !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbCheckMK)
                                            .addComponent(lbCheckMKMoi)
                                            .addComponent(txtMKCu, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(txtMKNew))
                                        .addGap(107, 107, 107))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbCheckXNMK)
                                        .addGap(228, 228, 228))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hintLabel1)
                                .addGap(100, 100, 100)))
                        .addComponent(changePassStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hintLabel)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(changePassStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hintLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lbCheckMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMKNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCheckMKMoi)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCheckXNMK))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        String oldPass = txtMKCu.getText();
        String newPass = txtMKNew.getText();
        String newPassAgain = txtXacNhan.getText();
        if (validatePass(oldPass, newPass, newPassAgain)) {
            if (login.updatePassHV(newPass, maHV)) {
                JOptionPane.showMessageDialog(this, "Đổi Mật Khẩu Thành Công!");
                txtMKCu.setText("");
                txtMKNew.setText("");
                txtXacNhan.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Đổi Mật Khẩu Thất Bại!");
            }
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void txtXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDoiMKHV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDoiMKHV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDoiMKHV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDoiMKHV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDoiMKHV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JLabel changePassStatus;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel hintLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCheckMK;
    private javax.swing.JLabel lbCheckMKMoi;
    private javax.swing.JLabel lbCheckXNMK;
    private javax.swing.JTextField txtMKCu;
    private javax.swing.JPasswordField txtMKNew;
    private javax.swing.JPasswordField txtXacNhan;
    // End of variables declaration//GEN-END:variables
}
