/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.NhanVien;
import service.impl.adminServiceImpl;

/**
 *
 * @author Dell
 */
public class formDoiMKAdmin extends javax.swing.JFrame {

    private adminServiceImpl adsv = new adminServiceImpl();
    public String maNV;

    /**
     * Creates new form HVdoiMK
     */
    public formDoiMKAdmin() {
        initComponents();
    }

    public formDoiMKAdmin(String ma) {
        initComponents();
        setLocationRelativeTo(null);
        maNV = ma;
        jLabel5.setText("Nhân Viên "+ma);
    }

    public boolean validatePass(String oldPass, String newPass, String newPassAgain) {
        NhanVien nv = adsv.getOneAdmin(maNV);
        String check1 = "^[a-zA-Z0-9]{8,49}$";
        String check2 = "^[a-zA-Z0-9]*[0-9]+[a-zA-Z0-9]*";
        String check3 = "^[a-zA-Z0-9]*[a-zA-Z]+[a-zA-Z0-9]*";
        if (oldPass.isEmpty()) {
            lbCheckMK.setText("Mật Khẩu Hiện Tại Chưa Được Nhâp!");
            return false;
        }
        if (!oldPass.equalsIgnoreCase(nv.getMatKhau())) {
            lbCheckMK.setText("Mật Khẩu Sai!");
            return false;
        }
        if (newPass.isEmpty()) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Chưa Được Nhập!");
            return false;
        }
        if (newPass.length() < 8 || newPass.length() > 49) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Tối Thiểu Từ 8 Kí Tự Và Tối Đa 49 Kí Tự!");
            return false;
        }
        if (newPass.equals(oldPass)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Không Được Trùng Với Mật Khẩu Hiện Tại!");
            return false;
        }
        if (!newPass.matches(check3) || !newPass.matches(check2)
                || !newPass.matches(check1)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("Mật Khẩu Mới Phải Đúng Định Dạng!");
            return false;
        }
        if (newPassAgain.isEmpty()) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("");
            lbCheckXNMK.setText("Mật Khẩu Xác Nhận Chưa Được Nhập!");
            return false;
        }
        if (!newPass.equals(newPassAgain)) {
            lbCheckMK.setText("");
            lbCheckMKMoi.setText("");
            lbCheckXNMK.setText("Mật Khẩu Xác Nhận Phải Trùng Với Mật Khẩu Mới!");
            return false;
        }
        lbCheckMK.setText("");
        lbCheckMKMoi.setText("");
        lbCheckXNMK.setText("");
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        changePassStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hintLabel = new javax.swing.JLabel();
        lbCheckMK = new javax.swing.JLabel();
        btnDoiMK = new javax.swing.JButton();
        lbCheckMKMoi = new javax.swing.JLabel();
        lbCheckXNMK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hintLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu Mới");

        changePassStatus.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        changePassStatus.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Xác Nhận Mật Khẩu");

        hintLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        hintLabel.setForeground(new java.awt.Color(54, 33, 89));
        hintLabel.setText("Thay đổi mật khẩu. Mật khẩu mới phải đạt tối thiểu 8 ký tự.");

        lbCheckMK.setForeground(new java.awt.Color(255, 0, 0));
        lbCheckMK.setText("jLabel4");

        btnDoiMK.setBackground(new java.awt.Color(204, 255, 153));
        btnDoiMK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(51, 153, 255));
        btnDoiMK.setText("Thay Đổi");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        lbCheckMKMoi.setForeground(new java.awt.Color(255, 0, 0));
        lbCheckMKMoi.setText("jLabel5");

        lbCheckXNMK.setForeground(new java.awt.Color(255, 0, 0));
        lbCheckXNMK.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mật Khẩu Cũ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("THAY ĐỔI MẬT KHẨU");

        hintLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        hintLabel1.setForeground(new java.awt.Color(54, 33, 89));
        hintLabel1.setText("Mật Khẩu Có Thể Là Số , Chữ Thường Hoặc In Hoa , Không Được Phép Có Kí Tự Đặc Biệt !");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(hintLabel1)
                        .addGap(124, 124, 124)
                        .addComponent(changePassStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCheckMKMoi)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField2)
                                .addComponent(jPasswordField1))
                            .addComponent(lbCheckXNMK)
                            .addComponent(lbCheckMK)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(hintLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(changePassStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hintLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lbCheckMK)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCheckMKMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbCheckXNMK)
                .addGap(46, 46, 46)
                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        String oldPass = jPasswordField1.getText();
        String newPass = jPasswordField2.getText();
        String newPassAgain = jPasswordField3.getText();
        if (validatePass(oldPass, newPass, newPassAgain)) {
            if (adsv.updatePass(newPass, maNV)) {
                JOptionPane.showMessageDialog(this, "Đổi Mật Khẩu Thành Công!");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Đổi Mật Khẩu Thất Bại!");
            }
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menuAdmin m = new menuAdmin();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDoiMKAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDoiMKAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDoiMKAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDoiMKAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDoiMKAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JLabel changePassStatus;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel hintLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JLabel lbCheckMK;
    private javax.swing.JLabel lbCheckMKMoi;
    private javax.swing.JLabel lbCheckXNMK;
    // End of variables declaration//GEN-END:variables
}
