/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.DongHocPhi;
import model.HocVien;
import model.MonHoc;
import service.impl.adminServiceImpl;

/**
 *
 * @author acer
 */
public class FormQLDHP extends javax.swing.JFrame {

    private DefaultTableModel tbmodel = new DefaultTableModel();
    private List<DongHocPhi> listDHP = new ArrayList<>();
    private List<DongHocPhi> listAllDHP = new ArrayList<>();
    private adminServiceImpl admsv = new adminServiceImpl();
    private int pageIndex = 1;
    private int pageNumber = 5;

    /**
     * Creates new form FormQLDHP
     */
    public FormQLDHP() {
        initComponents();
        setLocationRelativeTo(null);
        listAllDHP = admsv.getListDHP();
        listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
        BigDecimal sumMoney = admsv.thongKeTongTien();
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        String tt = formatter.format(sumMoney) + " VNĐ";
        lbSumMoney.setText("Tổng Số Học Phí Đã Thu : " + tt);
        int sl = admsv.tkSLHV();
        lbSumHV.setText("Số Học Viên Đóng Học Phí : " + sl);
        loadData(listDHP);
    }

    public void loadData(List<DongHocPhi> list) {
        jTable1.setModel(tbmodel);
        tbmodel.setRowCount(0);
        String title[] = {"Học Viên", "Môn Học", "Ngày Đóng", "Tiền Đóng"};
        tbmodel.setColumnIdentifiers(title);
        for (DongHocPhi dhp : list) {
            DecimalFormat formatter = new DecimalFormat("###,###,###");
            MonHoc mh = admsv.getMHByID(dhp.getIdMonHoc());
            HocVien hv = admsv.getHVById(dhp.getIdHocVien());
            tbmodel.addRow(new Object[]{hv.getHo() + " " + hv.getTenDem() + " " + hv.getTen(),
                mh.getTenMon(), dhp.getNgayDong(), formatter.format(dhp.getTienDong()) + " VNĐ"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbSumMoney = new javax.swing.JLabel();
        lbSumHV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("?/?");

        lbSumMoney.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSumMoney.setText("jLabel2");

        lbSumHV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSumHV.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSumMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSumHV, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(84, 84, 84)
                .addComponent(lbSumMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbSumHV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (listAllDHP.size() % 5 != 0) {
            if (pageIndex <= 1) {
                pageIndex = listAllDHP.size() / 5 + 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5 + 1;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            } else {
                pageIndex -= 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5 + 1;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            }
        } else {
            if (pageIndex <= 1) {
                pageIndex = listAllDHP.size() / 5;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            } else {
                pageIndex -= 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (listAllDHP.size() % 5 != 0) {
            if (pageIndex >= listAllDHP.size() / 5 + 1) {
                pageIndex = 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5 + 1;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            } else {
                pageIndex += 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5 + 1;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            }
        } else {
            if (pageIndex >= listAllDHP.size() / 5) {
                pageIndex = 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            } else {
                pageIndex += 1;
                listDHP = admsv.getListPTDHP(pageIndex, pageNumber);
                int maxPage = listAllDHP.size() / 5;
                jLabel1.setText(pageIndex + "/" + maxPage);
                loadData(listDHP);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormDHPAdmin f = new FormDHPAdmin(this, true);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLDHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLDHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLDHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLDHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLDHP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbSumHV;
    private javax.swing.JLabel lbSumMoney;
    // End of variables declaration//GEN-END:variables
}
